<?php

declare(strict_types=1);

namespace App\DataFixtures;

use App\Entity\Person;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class PersonFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $persons = [
            // Case 1: Both name and firstname have values
            ['name' => 'John', 'firstname' => 'Michael', 'surname' => 'Doe', 'email' => 'john.michael@example.com', 'age' => 30],
            ['name' => 'Jane', 'firstname' => 'Elizabeth', 'surname' => 'Smith', 'email' => 'jane.elizabeth@example.com', 'age' => 25],
            ['name' => 'Robert', 'firstname' => 'James', 'surname' => 'Wilson', 'email' => 'robert.james@example.com', 'age' => 40],

            // Case 2: name has value, firstname is null (will be generated by name_fallback)
            ['name' => 'Alice', 'firstname' => null, 'surname' => 'Brown', 'email' => 'alice@example.com', 'age' => 28],
            ['name' => 'Charlie', 'firstname' => null, 'surname' => 'Davis', 'email' => 'charlie@example.com', 'age' => 35],
            ['name' => 'David', 'firstname' => null, 'surname' => 'Miller', 'email' => 'david@example.com', 'age' => 45],

            // Case 3: firstname has value, name is null (will be generated by name_fallback)
            ['name' => null, 'firstname' => 'Emma', 'surname' => 'Jones', 'email' => 'emma@example.com', 'age' => 22],
            ['name' => null, 'firstname' => 'Frank', 'surname' => 'Taylor', 'email' => 'frank@example.com', 'age' => 50],
            ['name' => null, 'firstname' => 'Grace', 'surname' => 'Anderson', 'email' => 'grace@example.com', 'age' => 33],

            // Case 4: Both name and firstname are null (both will be generated)
            ['name' => null, 'firstname' => null, 'surname' => 'Thomas', 'email' => 'person1@example.com', 'age' => 29],
            ['name' => null, 'firstname' => null, 'surname' => 'Martinez', 'email' => 'person2@example.com', 'age' => 18],
            ['name' => null, 'firstname' => null, 'surname' => 'Rodriguez', 'email' => 'person3@example.com', 'age' => 100],

            // Case 5: More examples with both values
            ['name' => 'Karen', 'firstname' => 'Marie', 'surname' => 'White', 'email' => 'karen.marie@example.com', 'age' => 38],
            ['name' => 'Lucas', 'firstname' => 'Paul', 'surname' => 'Harris', 'email' => 'lucas.paul@example.com', 'age' => 27],
            ['name' => 'Maria', 'firstname' => 'Isabel', 'surname' => 'Clark', 'email' => 'maria.isabel@example.com', 'age' => 31],

            // Case 6: More examples with name only
            ['name' => 'Noah', 'firstname' => null, 'surname' => 'Lewis', 'email' => 'noah@example.com', 'age' => 42],
            ['name' => 'Olivia', 'firstname' => null, 'surname' => 'Walker', 'email' => 'olivia@example.com', 'age' => 26],

            // Case 7: More examples with firstname only
            ['name' => null, 'firstname' => 'Peter', 'surname' => 'Hall', 'email' => 'peter@example.com', 'age' => 39],
            ['name' => null, 'firstname' => 'Quinn', 'surname' => 'Allen', 'email' => 'quinn@example.com', 'age' => 24],
        ];

        foreach ($persons as $personData) {
            $person = new Person();
            $person->setName($personData['name']);
            $person->setFirstname($personData['firstname']);
            $person->setSurname($personData['surname']);
            $person->setEmail($personData['email']);
            $person->setAge($personData['age']);
            $person->setAnonymized(false);

            $manager->persist($person);
        }

        $manager->flush();
    }
}
