--
-- PostgreSQL database dump
--

\restrict YwcrT6zk3O5HgabxhD45TbUjK1aNHsPz9FzZV2tQ6qZw3VoviouKNrNVnCsgCO8

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customers; Type: TABLE; Schema: public; Owner: demo_user
--

CREATE TABLE public.customers (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(50) NOT NULL,
    anonymized boolean DEFAULT false NOT NULL,
    reference_code character varying(50) DEFAULT NULL::character varying
);


ALTER TABLE public.customers OWNER TO demo_user;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: demo_user
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_subscriptions; Type: TABLE; Schema: public; Owner: demo_user
--

CREATE TABLE public.email_subscriptions (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    status character varying(50) NOT NULL,
    backup_email character varying(100) DEFAULT NULL::character varying,
    subscribed_at timestamp(0) without time zone NOT NULL,
    unsubscribed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    source character varying(50) NOT NULL,
    notes text,
    anonymized boolean DEFAULT false NOT NULL
);


ALTER TABLE public.email_subscriptions OWNER TO demo_user;

--
-- Name: email_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: demo_user
--

ALTER TABLE public.email_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: demo_user
--

CREATE TABLE public.employees (
    id integer NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    username character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(20) DEFAULT NULL::character varying,
    birth_date date,
    age integer NOT NULL,
    department character varying(100) NOT NULL,
    previous_company character varying(100) DEFAULT NULL::character varying,
    hire_date timestamp(0) without time zone NOT NULL,
    anonymized boolean DEFAULT false NOT NULL
);


ALTER TABLE public.employees OWNER TO demo_user;

--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: demo_user
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoices; Type: TABLE; Schema: public; Owner: demo_user
--

CREATE TABLE public.invoices (
    id integer NOT NULL,
    invoice_number character varying(50) NOT NULL,
    company_name character varying(255) NOT NULL,
    company_address character varying(255) NOT NULL,
    bank_account character varying(34) DEFAULT NULL::character varying,
    credit_card character varying(19) DEFAULT NULL::character varying,
    amount numeric(10,2) NOT NULL,
    issue_date timestamp(0) without time zone NOT NULL,
    due_date timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    status character varying(50) NOT NULL,
    anonymized boolean DEFAULT false NOT NULL
);


ALTER TABLE public.invoices OWNER TO demo_user;

--
-- Name: invoices_id_seq; Type: SEQUENCE; Schema: public; Owner: demo_user
--

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: demo_user
--

CREATE TABLE public.orders (
    id integer NOT NULL,
    order_number character varying(50) DEFAULT NULL::character varying,
    shipping_address character varying(255) NOT NULL,
    billing_address character varying(255) DEFAULT NULL::character varying,
    total_amount numeric(10,2) NOT NULL,
    order_date timestamp(0) without time zone NOT NULL,
    status character varying(50) NOT NULL,
    customer_email character varying(255) DEFAULT NULL::character varying,
    anonymized boolean DEFAULT false NOT NULL,
    type_id integer
);


ALTER TABLE public.orders OWNER TO demo_user;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: demo_user
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: demo_user
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    price numeric(10,2) NOT NULL,
    image_url character varying(255) DEFAULT NULL::character varying,
    status character varying(50) NOT NULL,
    created_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    anonymized boolean DEFAULT false NOT NULL
);


ALTER TABLE public.products OWNER TO demo_user;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: demo_user
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_logs; Type: TABLE; Schema: public; Owner: demo_user
--

CREATE TABLE public.system_logs (
    id integer NOT NULL,
    session_id character varying(36) NOT NULL,
    ip_address character varying(45) NOT NULL,
    mac_address character varying(17) NOT NULL,
    api_key character varying(255) NOT NULL,
    token_hash character varying(64) NOT NULL,
    location character varying(50) NOT NULL,
    theme_color character varying(7) NOT NULL,
    is_active boolean NOT NULL,
    score numeric(10,2) NOT NULL,
    log_file character varying(255) NOT NULL,
    metadata text,
    description text,
    log_level character varying(50) NOT NULL,
    country_code character varying(2) NOT NULL,
    language_code character varying(5) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    user_id_hash character varying(64) DEFAULT NULL::character varying,
    process_status character varying(50) DEFAULT NULL::character varying,
    data_classification character varying(50) DEFAULT NULL::character varying,
    anonymized boolean DEFAULT false NOT NULL
);


ALTER TABLE public.system_logs OWNER TO demo_user;

--
-- Name: system_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: demo_user
--

ALTER TABLE public.system_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: types; Type: TABLE; Schema: public; Owner: demo_user
--

CREATE TABLE public.types (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255) DEFAULT NULL::character varying
);


ALTER TABLE public.types OWNER TO demo_user;

--
-- Name: types_id_seq; Type: SEQUENCE; Schema: public; Owner: demo_user
--

ALTER TABLE public.types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: demo_user
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    firstname character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    age integer NOT NULL,
    phone character varying(20) DEFAULT NULL::character varying,
    iban character varying(34) DEFAULT NULL::character varying,
    creditcard character varying(19) DEFAULT NULL::character varying,
    status character varying(50) NOT NULL,
    anonymized boolean DEFAULT false NOT NULL
);


ALTER TABLE public.users OWNER TO demo_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: demo_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: demo_user
--

COPY public.customers (id, email, name, status, anonymized, reference_code) FROM stdin;
59	customer1@example.com	Customer One	active	f	CUST-00000001
60	customer2@example.com	Customer Two	active	f	CUST-00000002
61	customer3@example.com	Customer Three	active	f	CUST-00000003
62	customer4@example.com	Customer Four	active	f	CUST-00000004
63	customer5@example.com	Customer Five	active	f	CUST-00000005
64	customer6@example.com	Customer Six	active	f	CUST-00000006
65	customer7@example.com	Customer Seven	active	f	CUST-00000007
66	customer8@example.com	Customer Eight	active	f	CUST-00000008
67	customer9@example.com	Customer Nine	active	f	CUST-00000009
68	customer10@example.com	Customer Ten	active	f	CUST-00000010
69	customer11@example.com	Customer Eleven	active	f	CUST-00000011
70	customer12@example.com	Customer Twelve	active	f	CUST-00000012
71	customer13@example.com	Customer Thirteen	active	f	CUST-00000013
72	customer14@example.com	Customer Fourteen	active	f	CUST-00000014
73	customer15@example.com	Customer Fifteen	active	f	CUST-00000015
74	customer16@example.com	Customer Sixteen	inactive	f	CUST-00000016
75	customer17@example.com	Customer Seventeen	inactive	f	CUST-00000017
76	customer18@example.com	Customer Eighteen	inactive	f	CUST-00000018
77	customer19@example.com	Customer Nineteen	inactive	f	CUST-00000019
78	customer20@example.com	Customer Twenty	inactive	f	CUST-00000020
79	customer21@example.com	Customer Twenty-One	active	f	CUST-00000021
80	customer22@example.com	Customer Twenty-Two	active	f	CUST-00000022
81	customer23@example.com	Customer Twenty-Three	active	f	CUST-00000023
82	customer24@example.com	Customer Twenty-Four	active	f	CUST-00000024
83	customer25@example.com	Customer Twenty-Five	active	f	CUST-00000025
\.


--
-- Data for Name: email_subscriptions; Type: TABLE DATA; Schema: public; Owner: demo_user
--

COPY public.email_subscriptions (id, email, name, status, backup_email, subscribed_at, unsubscribed_at, source, notes, anonymized) FROM stdin;
\.


--
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: demo_user
--

COPY public.employees (id, first_name, last_name, username, email, phone, birth_date, age, department, previous_company, hire_date, anonymized) FROM stdin;
13	Alice	Johnson	alice.johnson	alice.johnson@company.com	+1-555-0101	1985-05-15	38	HR	HR Solutions Inc.	2021-01-19 18:33:49	f
14	Bob	Smith	bob.smith	bob.smith@company.com	+1-555-0102	1990-08-20	33	HR	People Management LLC	2023-01-19 18:33:49	f
15	Carol	Williams	carol.williams	carol.williams@company.com	+1-555-0103	1988-12-10	35	HR	Talent Acquisition Corp	2022-01-19 18:33:49	f
16	David	Brown	david.brown	david.brown@company.com	+1-555-0104	1992-03-25	31	Engineering	Tech Innovations Ltd.	2024-01-19 18:33:49	f
17	Emma	Jones	emma.jones	emma.jones@company.com	+1-555-0105	1995-07-30	28	Engineering	Software Solutions Inc.	2025-01-19 18:33:49	f
18	Frank	Garcia	frank.garcia	frank.garcia@company.com	+1-555-0106	1987-11-05	36	Sales	Sales Pro LLC	2020-01-19 18:33:49	f
19	Grace	Miller	grace.miller	grace.miller@company.com	+1-555-0107	1993-01-18	31	Marketing	Digital Marketing Corp	2023-01-19 18:33:49	f
20	Henry	Davis	henry.davis	henry.davis@company.com	+1-555-0108	1989-09-22	34	Engineering	Code Masters Inc.	2022-01-19 18:33:49	f
21	Ivy	Rodriguez	ivy.rodriguez	ivy.rodriguez@company.com	+1-555-0109	1994-04-12	29	Sales	Business Solutions LLC	2024-01-19 18:33:49	f
22	Jack	Martinez	jack.martinez	jack.martinez@company.com	+1-555-0110	1991-06-28	32	Marketing	Creative Agency Ltd.	2025-01-19 18:33:49	f
23	Kate	Anderson	kate.anderson	kate.anderson@company.com	+1-555-0111	1996-10-15	27	Engineering	Startup Tech Inc.	2025-07-19 18:33:49	f
24	Liam	Taylor	liam.taylor	liam.taylor@company.com	+1-555-0112	1986-02-08	37	Sales	Enterprise Sales Corp	2019-01-19 18:33:49	f
\.


--
-- Data for Name: invoices; Type: TABLE DATA; Schema: public; Owner: demo_user
--

COPY public.invoices (id, invoice_number, company_name, company_address, bank_account, credit_card, amount, issue_date, due_date, status, anonymized) FROM stdin;
9	INV-000000000001	Acme Corporation	100 Business Park, New York, NY 10001	ES9121000418450200051332	4532123456789012	1250.50	2025-10-19 18:33:49	2026-02-15 18:33:49	paid	f
10	INV-000000000002	Tech Solutions Inc.	200 Innovation Drive, San Francisco, CA 94102	ES9121000418450200051333	5555123456789012	3450.75	2025-11-19 18:33:49	2026-02-16 18:33:49	pending	f
11	INV-000000000003	Global Services LLC	300 Commerce Blvd, Chicago, IL 60601	ES9121000418450200051334	4111111111111111	890.25	2025-12-19 18:33:49	2026-02-17 18:33:49	paid	f
12	INV-000000000004	Digital Marketing Corp	400 Media Street, Los Angeles, CA 90001	ES9121000418450200051335	378282246310005	5678.90	2025-12-29 18:33:49	2026-01-26 18:33:49	overdue	f
13	INV-000000000005	Software Development Ltd.	500 Code Avenue, Seattle, WA 98101	ES9121000418450200051336	6011111111111117	2345.67	2026-01-05 18:33:49	2026-02-04 18:33:49	pending	f
14	INV-000000000006	Consulting Group Inc.	600 Strategy Way, Boston, MA 02101	ES9121000418450200051337	5105105105105100	4567.89	2026-01-12 18:33:49	2026-02-11 18:33:49	paid	f
15	INV-000000000007	E-commerce Solutions LLC	700 Online Plaza, Miami, FL 33101	ES9121000418450200051338	4242424242424242	1234.56	2026-01-14 18:33:49	2026-02-13 18:33:49	pending	f
16	INV-000000000008	Cloud Services Corp	800 Cloud Drive, Austin, TX 78701	ES9121000418450200051339	371449635398431	7890.12	2026-01-15 18:33:49	2026-02-14 18:33:49	paid	f
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: demo_user
--

COPY public.orders (id, order_number, shipping_address, billing_address, total_amount, order_date, status, customer_email, anonymized, type_id) FROM stdin;
14	ORD-0000000001	123 Main St, New York, NY 10001	123 Main St, New York, NY 10001	299.99	2025-11-19 18:33:49	completed	customer1@example.com	f	\N
15	ORD-0000000002	456 Oak Ave, Los Angeles, CA 90001	456 Oak Ave, Los Angeles, CA 90001	599.99	2025-12-19 18:33:49	completed	customer2@example.com	f	\N
16	ORD-0000000003	789 Pine Rd, Chicago, IL 60601	789 Pine Rd, Chicago, IL 60601	149.99	2025-12-29 18:33:49	completed	customer3@example.com	f	\N
17	ORD-0000000004	321 Elm St, Houston, TX 77001	321 Elm St, Houston, TX 77001	899.99	2026-01-05 18:33:49	completed	customer4@example.com	f	\N
18	ORD-0000000005	654 Maple Dr, Phoenix, AZ 85001	654 Maple Dr, Phoenix, AZ 85001	249.99	2026-01-12 18:33:49	completed	customer5@example.com	f	\N
19	ORD-0000000006	987 Cedar Ln, Philadelphia, PA 19101	987 Cedar Ln, Philadelphia, PA 19101	399.99	2026-01-14 18:33:49	completed	customer6@example.com	f	\N
20	ORD-0000000007	147 Birch Way, San Antonio, TX 78201	147 Birch Way, San Antonio, TX 78201	549.99	2026-01-15 18:33:49	completed	customer7@example.com	f	\N
21	ORD-0000000008	258 Willow St, San Diego, CA 92101	258 Willow St, San Diego, CA 92101	199.99	2026-01-16 18:33:49	completed	customer8@example.com	f	\N
22	ORD-0000000009	369 Spruce Ave, Dallas, TX 75201	369 Spruce Ave, Dallas, TX 75201	799.99	2026-01-17 18:33:49	completed	customer9@example.com	f	\N
23	ORD-0000000010	741 Ash Blvd, San Jose, CA 95101	741 Ash Blvd, San Jose, CA 95101	349.99	2026-01-18 18:33:49	completed	customer10@example.com	f	\N
24	ORD-0000000011	852 Poplar Rd, Austin, TX 78701	852 Poplar Rd, Austin, TX 78701	449.99	2026-01-12 18:33:49	pending	customer11@example.com	f	\N
25	ORD-0000000012	963 Hickory Dr, Jacksonville, FL 32201	963 Hickory Dr, Jacksonville, FL 32201	299.99	2026-01-14 18:33:49	processing	customer12@example.com	f	\N
26	ORD-0000000013	159 Sycamore Ln, Fort Worth, TX 76101	159 Sycamore Ln, Fort Worth, TX 76101	649.99	2026-01-16 18:33:49	shipped	customer13@example.com	f	\N
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: demo_user
--

COPY public.products (id, name, description, price, image_url, status, created_at, anonymized) FROM stdin;
11	Laptop Pro 15	High-performance laptop with 16GB RAM and 512GB SSD	1299.99	https://example.com/products/laptop-pro-15.jpg	active	2025-07-19 18:33:49	f
12	Wireless Mouse	Ergonomic wireless mouse with long battery life	29.99	https://example.com/products/mouse.jpg	active	2025-10-19 18:33:49	f
13	Mechanical Keyboard	RGB mechanical keyboard with cherry switches	149.99	https://example.com/products/keyboard.jpg	active	2025-11-19 18:33:49	f
14	4K Monitor	27-inch 4K UHD monitor with HDR support	599.99	https://example.com/products/monitor.jpg	active	2025-01-19 18:33:49	f
15	USB-C Hub	Multi-port USB-C hub with HDMI and SD card reader	49.99	https://example.com/products/hub.jpg	active	2025-09-19 18:33:49	f
16	Webcam HD	1080p HD webcam with auto-focus and noise cancellation	79.99	https://example.com/products/webcam.jpg	active	2025-08-19 18:33:49	f
17	Gaming Headset	7.1 surround sound gaming headset with RGB lighting	129.99	https://example.com/products/headset.jpg	active	2025-05-19 18:33:49	f
18	External SSD 1TB	Portable external SSD with USB 3.2 Gen 2	199.99	https://example.com/products/ssd.jpg	active	2025-06-19 18:33:49	f
19	Old Product Model	This product is no longer available	99.99	\N	discontinued	2024-01-19 18:33:49	f
20	Pending Product	Product awaiting approval	199.99	\N	pending	2026-01-12 18:33:49	f
\.


--
-- Data for Name: system_logs; Type: TABLE DATA; Schema: public; Owner: demo_user
--

COPY public.system_logs (id, session_id, ip_address, mac_address, api_key, token_hash, location, theme_color, is_active, score, log_file, metadata, description, log_level, country_code, language_code, created_at, user_id_hash, process_status, data_classification, anonymized) FROM stdin;
\.


--
-- Data for Name: types; Type: TABLE DATA; Schema: public; Owner: demo_user
--

COPY public.types (id, name, description) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: demo_user
--

COPY public.users (id, email, firstname, lastname, age, phone, iban, creditcard, status, anonymized) FROM stdin;
46	john.doe@example.com	John	Doe	30	+34612345678	ES9121000418450200051332	4532015112830366	active	f
47	jane.smith@example.com	Jane	Smith	25	+34698765432	ES9121000418450200051333	4532015112830367	active	f
48	bob.wilson@example.com	Bob	Wilson	40	+34655512345	ES9121000418450200051334	4532015112830368	active	f
49	alice.brown@example.com	Alice	Brown	28	+34611122233	ES9121000418450200051335	4532015112830369	active	f
50	charlie.davis@example.com	Charlie	Davis	35	+34644455566	ES9121000418450200051336	4532015112830370	active	f
51	david.miller@example.com	David	Miller	45	+34677788899	ES9121000418450200051337	4532015112830371	inactive	f
52	emma.jones@example.com	Emma	Jones	22	+34622233344	ES9121000418450200051338	4532015112830372	inactive	f
53	frank.taylor@example.com	Frank	Taylor	50	\N	\N	\N	active	f
54	grace.anderson@example.com	Grace	Anderson	33	+34633344455	\N	4532015112830373	active	f
55	henry.thomas@example.com	Henry	Thomas	29	\N	ES9121000418450200051339	\N	active	f
56	isabella.martinez@example.com	Isabella	Martinez	18	+34644455566	ES9121000418450200051340	4532015112830374	active	f
57	james.rodriguez@example.com	James	Rodriguez	100	+34655566677	ES9121000418450200051341	4532015112830375	active	f
58	karen.white@example.com	Karen	White	38	+34666677788	ES9121000418450200051342	4532015112830376	active	f
59	lucas.harris@example.com	Lucas	Harris	27	+34677788899	ES9121000418450200051343	4532015112830377	active	f
60	maria.clark@example.com	Maria	Clark	31	+34688899900	ES9121000418450200051344	4532015112830378	active	f
61	noah.lewis@example.com	Noah	Lewis	42	+34699900011	ES9121000418450200051345	4532015112830379	active	f
62	olivia.walker@example.com	Olivia	Walker	26	+34600011122	ES9121000418450200051346	4532015112830380	active	f
63	peter.hall@example.com	Peter	Hall	39	+34611122233	ES9121000418450200051347	4532015112830381	active	f
64	quinn.allen@example.com	Quinn	Allen	24	+34622233344	ES9121000418450200051348	4532015112830382	active	f
65	rachel.young@example.com	Rachel	Young	36	+34633344455	ES9121000418450200051349	4532015112830383	active	f
\.


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo_user
--

SELECT pg_catalog.setval('public.customers_id_seq', 133, true);


--
-- Name: email_subscriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo_user
--

SELECT pg_catalog.setval('public.email_subscriptions_id_seq', 80, true);


--
-- Name: employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo_user
--

SELECT pg_catalog.setval('public.employees_id_seq', 48, true);


--
-- Name: invoices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo_user
--

SELECT pg_catalog.setval('public.invoices_id_seq', 32, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo_user
--

SELECT pg_catalog.setval('public.orders_id_seq', 26, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo_user
--

SELECT pg_catalog.setval('public.products_id_seq', 40, true);


--
-- Name: system_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo_user
--

SELECT pg_catalog.setval('public.system_logs_id_seq', 10, true);


--
-- Name: types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo_user
--

SELECT pg_catalog.setval('public.types_id_seq', 14, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo_user
--

SELECT pg_catalog.setval('public.users_id_seq', 105, true);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: email_subscriptions email_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.email_subscriptions
    ADD CONSTRAINT email_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: system_logs system_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.system_logs
    ADD CONSTRAINT system_logs_pkey PRIMARY KEY (id);


--
-- Name: types types_pkey; Type: CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.types
    ADD CONSTRAINT types_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_e52ffdeec54c8c93; Type: INDEX; Schema: public; Owner: demo_user
--

CREATE INDEX idx_e52ffdeec54c8c93 ON public.orders USING btree (type_id);


--
-- Name: uniq_ba82c300f85e0677; Type: INDEX; Schema: public; Owner: demo_user
--

CREATE UNIQUE INDEX uniq_ba82c300f85e0677 ON public.employees USING btree (username);


--
-- Name: orders fk_e52ffdeec54c8c93; Type: FK CONSTRAINT; Schema: public; Owner: demo_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_e52ffdeec54c8c93 FOREIGN KEY (type_id) REFERENCES public.types(id);


--
-- PostgreSQL database dump complete
--

\unrestrict YwcrT6zk3O5HgabxhD45TbUjK1aNHsPz9FzZV2tQ6qZw3VoviouKNrNVnCsgCO8

